from typing import Protocol, TextIO


class Object(Protocol):
    name: str
    def write_decl_to_file(self, f: TextIO, extern: bool = False) -> None: ...
    def write_reg_to_file(self, f: TextIO) -> None: ...
    def write_python_subclass(self, f: TextIO) -> None: ...
