[project]
name = "nettle"
version = "2026.2"
description = "Python bindings to the nettle cryptographic library"
readme = "README.md"
license = "GPL-3.0-or-later"
authors = [
    { name = "Henrik Rindlöw", email = "henrik@rindlow.se" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.11.10,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "sphinx>=9.1.0",
]

[tool.uv]
reinstall = true

[tool.ruff.lint]
preview = false

select = [
    "ALL", # include all the rules, including new ones
]

ignore = [
    "COM812",
    "D107",
    "D203",
    "D212",
    "Q000",
    "Q001",
]

